server:
  servlet:
    context-path: /world  # 所有的请求都必须以 /world 开始
#spring:
#  mvc:
#    contentnegotiation:
#      favor-parameter: true   # 开启参数方式的内容协商 默认为false

# 手动开启表单rest功能
#spring:
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
#  web:
#    resources:
#      static-locations: [classpath:/haha/]

  # 改变静态资源访问前缀
#  mvc:
#    static-path-pattern: /res/**  # 这个会导致favicon.ico功能失效
#   改变静态资源路径

#spring:
#  web:
#    resources:
#      add-mappings: false # 禁用静态资源 默认为true(不禁用)

#spring:
#  web:
#    resources:
#      cache:
#        period: 99 # 默认以秒为单位